workflows:
  default-workflow:
    name: Default Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
    triggering:
      events:
        - push
    when:
      changeset:
        includes:
          - '.'
    triggering:
      events:
        - pull_request
        - tag
      branch_patterns:
        - pattern: 'master'
          include: true
          source: false
        - pattern: 'develop*'
          include: true
          source: true
        - pattern: 'feature*'
          include: true
          source: true
      tag_patterns:
        - pattern: 'v1.0*'
          include: true
      cancel_previous_builds: true
    scripts:
      - |
        # set up local properties
        echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - flutter packages pub get
      - flutter build appbundle --debug
    artifacts:
      - build/**/outputs/bundle/**/*.aab
      - build/**/outputs/**/mapping.txt
    publishing:
      email:
        recipients:
          - kalgi@nevercode.io
