workflows:
  default-workflow:
    name: Default Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
    triggering:
      events:
        - push
        - tag
    branch_patterns:
      - pattern: '*'
        include: true
        source: true
    tag_patterns:
      - pattern: '*'
        include: true
    scripts:
      - |
        # set up local properties
        echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - |
        npm install --save-dev @commitlint/{config-conventional,cli}
        npm install husky --save-dev
      - flutter packages pub get
      - flutter build appbundle --debug
      - |
        set -e
        git log --format=%B -n 1 $FCI_COMMIT
    artifacts:
      - build/**/outputs/bundle/**/*.aab
      - build/**/outputs/**/mapping.txt
    publishing:
      email:
        recipients:
          - kalgi@nevercode.io
